---
title: Terms and Conditions
---
|Welcome to ShubhSambandh.com . In order to use the ShubhSambandh.com Site ("Site") you must Register as a member of the Site ("Member") and agree to be bound by these Terms of Use ("Agreement"). If you wish to become a Member and communicate with othe Members and make use of the service ("Service"), read these Terms of Use and follow the instructions in the Registration process. This Agreement sets out the legally binding terms for your membership. This Agreement may be modified by ShubhSambandh.com from time to time for which the members will be notified through email communication. Your continued use of the Site pursuant to such change will constitute deemed acceptance of such changes.|
| :- |
|` `ShubhSambandh.com to assist Mumbai Police / Statutory Investigation Agency|
|ShubhSambandh.com will endeavour to provide all possible assistance to the Mumbai Police (Cyber Crime Investigation Cell) or any other statutory investigation agency to tackl fraudulent users of ShubhSambandh.com, on being specifically instructed by the said authorities to do so.|
|To  report  fraud  or  misuse, write  to  us giving  full  details  of  your  case  a ***care@shubhsambandh.com***|
|Welcome to ShubhSambandh.com, your personal matchmaking platform. This Agreemen sets out the legally binding terms for your use of the Site and membership. This Agreement may be modified by ShubhSambandh.com from time to time. The membership and rights of admissions are reserved.|
|This Terms of Use is published in accordance with the Rule 3 (1) of the Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules, 2021.|

1. **Eligibility.**

You  must  be  at  least  18  years  of  age  or  over  to  Register  as  a  member  of ShubhSambandh.com or use this Site. Membership to the Site is void where prohibited. Your use of this Site represents and warrants that you have the right, authority, and capacity to enter into this Agreement and to abide by all of the terms and conditions of this Agreement. This site is not meant to encourage and/or promote illicit sexual relations or extra marital affairs or dating. If ShubhSambandh.com discovers or becomes aware that any member is using this site to promote or engage or indulge in illicit sexual relations or extra marital affairs or dating his/her membership will be terminated forthwith without any refund  and  without  any  liability  to  ShubhSambandh.com  .  ShubhSambandh.com  's discretion to terminate shall be final and binding. Our team will first verify the relevant documents like personal identity,education,address,etc. to enhance the authenticity of the registered profiles on our site. After this process only, the members’ profiles would be activated. The documents can be sent to our team at **care@shubhsambandh.com**

2. **Term.**

This Agreement will remain in full force and effect while you use the Site and/or are a Member of ShubhSambandh.com . You may terminate your membership at any time, for any reason by informing ShubhSambandh.com in writing to terminate your Membership. In the event you terminate your membership, you will not be entitled to a refund of any unutilized subscription fees. ShubhSambandh.com may terminate your access to the Site and/or your membership for any reason which shall be effective upon sending notice of termination to you at the email address you provide in your application for membership or such  other  email  address  as  you  may  later  provide  to  ShubhSambandh.com.  If ShubhSambandh.com  terminates  your  membership  because  of  your  breaching  the Agreement, you will not be entitled to any refund of any unused Subscription fees. Even after this Agreement is terminated, certain provisions will remain in effect including sections 4,5,7,9 -12, inclusive, of this Agreement.

3. **Non-Commercial Use by Members.**

The ShubhSambandh.com Site is for the personal use of individual members only, and may not be used in connection with any commercial endeavors. This includes providing links to other websites, whether deemed competitive to ShubhSambandh.com or otherwise. Organizations,  companies,  and/or  businesses  may  not  become  Members  of ShubhSambandh.com and should not use the ShubhSambandh.com Service or Site for any purpose. Illegal and/or unauthorized uses of the Site, including unauthorized framing of or linking to the Site will be investigated, and appropriate legal action will be taken, including without limitation, civil, criminal, and injunctive redress.

4. **Other Terms of Use by Members.**
- You may not engage in advertising to, or solicitation of, other Members to buy or sell any products or services through the Service. You will not transmit any chain letters or junk email to other ShubhSambandh.com Members. Although ShubhSambandh.com cannot monitor the conduct of its Members on the ShubhSambandh.com Site, it is also a violation of this Agreement to use any information obtained from the Service in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to any Member without their prior explicit consent. In order to protect ShubhSambandh.com and/or our Members from any abuse/misuse, ShubhSambandh.com reserves the right to restrict the number of communications/profile contacts & responses/emails which a Member may send to other Member(s) in any 24-hour period to a number which ShubhSambandh.com deems appropriate in its sole discretion. You will not send any messages to other Members that are obscene, lewd, licentious, and defamatory, promote hatred and/or are racial or abusive in any manner. Transmission of any such messages shall constitute a breach of this Agreement and ShubhSambandh.com Shall be entitled to terminate your membership forthwith. ShubhSambandh.com reserves the right to screen messages that you may send to other Member(s) and also regulate the number of your chat sessions in its sole discretion.
- You may not use any automated processes, including IRC Bots, EXE's, CGI or any other programs/scripts to view content on or communicate/contact/respond/interact with ShubhSambandh.com and/or its Members
- ShubhSambandh.com owns and retains all proprietary rights, including without limitation, all intellectual property rights in the ShubhSambandh.com Site and the ShubhSambandh.com Service. The Site contains the copyrighted material, trademarks, and other proprietary information of ShubhSambandh.com , and its licensors. Except for that information which is in the public domain or for which you have been given express written permission by ShubhSambandh.com , you shall not copy, modify, publish, transmit, distribute, perform, display, or sell any such proprietary information. All lawful, legal and non-objectionable messages (in the sole discretion of ShubhSambandh.com ), content and/or other information, content or material that you post on the site shall become the property of ShubhSambandh.com . ShubhSambandh.com reserves the right to scrutinize all such information, content and/or material posted on the site and shall have the exclusive right to either remove, edit and/or display such information, material and/or content as deemed appropriate.
- You understand and agree that ShubhSambandh.com may delete any content, messages, photos or profiles (collectively, "Content") that in the sole judgment of ShubhSambandh.com violates this Agreement or which might be offensive, 

  illegal, defamatory, obscene, libelous, or that might violate the rights, harm, or threaten the safety of other ShubhSambandh.com Members.

- You are solely responsible for the Content that you publish or display (hereinafter, "post") on the Site through the ShubhSambandh.com Service, or transmit to other ShubhSambandh.com Members. ShubhSambandh.com reserves the right to verify the authenticity of Content posted on the Site. In exercising this right, ShubhSambandh.com may ask you to provide any documentary or other form of evidence supporting the Content you post on the Site. If you fail to produce such evidence, or if such evidence does not in the reasonable opinion of ShubhSambandh.com establish or justify the claim, ShubhSambandh.com may, in its sole discretion, may remove that content or may even terminate your Membership without a refund of your subscription fees.
- By posting Content to any public area of ShubhSambandh.com , you automatically grant, and you represent and warrant that you have the right to grant, to ShubhSambandh.com , and other ShubhSambandh.com Members, an irrevocable, perpetual, non-exclusive, fully-paid, worldwide license to use, copy, perform, display, and distribute such information and content and to prepare derivative works of, or incorporate into other works, such information and content, and to grant and authorize sublicenses of the foregoing.
5. **Content Posted on the Site.**
- The following is a partial list of the kind of Content that is illegal or prohibited on the Site. ShubhSambandh.com will investigate and take appropriate legal action in its sole discretion against anyone who violates this provision, including without limitation, removing the offending communication from the Service and the Site and terminating the Membership of such violators without a refund. It includes (but is not limited to) Content that:
- Newly created profile will be checked for correctness and will be immediately activated after various verifications by ShubhSambandh.com.
- ShubhSambandh.com reserves the rights to discontinue, deactivate, or terminate profile if the profile in terms of bad manners and the profile contents are not acceptable if it contains violent language or wrong material.
- You are only liable for your connections with other members through ShubhSambandh.com. The content posted by members though will be verified, but ShubhSambandh cannot be held liable for any damages or wrong or misleading content.
- Contact information of member's profile will be displayed only to paid members.. ShubhSambandh.com reserves right to discontinue free membership at any time.
- Members agree that they are legally eligible to get married as far as the age is concerned as per their respective laws. ShubhSambandh.com will not be responsible for misuse of any facility/service it provides, which is in violation to the local government laws.
- Every member submitting his/her matrimonial profile is required to give all the facts essential for establishing a marital relation. Concealing facts relevant to marriage could result in loss or damage to any individual and for which, ShubhSambandh.com cannot be held responsible in any way.
- ShubhSambandh.com in no way guarantees the genuineness of the information provided by its members.
- Members will not have any claim against ShubhSambandh.com for any time delay in posting their information into ShubhSambandh.com website due to any technical reasons.
- ShubhSambandh.com is not liable for damages caused due to incorrectness of the information provided by its members regarding the religion, caste or creed or any other personal information. If the members' profile is deemed to be unfit, ShubhSambandh.com has the right to delete, alter or refuse the same at any point of time after notice and relevant communication.  
- ShubhSambandh.com cannot be held responsible for any loss or damage resulting from discontinuation of the service. In the case of business discontinuity, ShubhSambandh.com is liable to refund maximum of 50% of unused fees(of remaining time). ShubhSambandh.com will also not be responsible for any damage caused due to others accessing members profile.
- ShubhSambandh.com cannot guarantee that you as an applicant will receive responses from other members and hence cannot be held responsible for no replies. In this case we cannot give any refunds or credits. Though from our support team, you will receive all the help that you need with respect to your queries, doubts & technical difficulties(like error in payment processing).
- However, ShubhSambandh.com is not legally responsible for any delay in operation due to technical or other reasons.

Following (but not limited to) are the reasons which can result in the member’s profile be terminated by ShubhSambandh.com:

- Harasses or advocates harassment of another person;
- Involves the transmission of "junk mail", "chain letters," or unsolicited mass mailing or "spamming";
- Promotes information that the person posting it is aware that it is false, misleading or promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;
- Promotes an illegal or unauthorized copy of another person's copyrighted work, such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;
- Contains restricted or password only access pages, or hidden pages or images (those not linked to or from another accessible page) ;
- Displays pornographic or sexually explicit material of any kind;
- Provides material that exploits people under the age of 18 years in a sexual or violent manner, or solicits personal information from anyone under the age of 18 years;
- Provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;
- Solicits passwords or personal identifying information for commercial or unlawful purposes from other users / Members; and
- Engages in commercial activities and/or sales without the prior written consent of ShubhSambandh.com such as contests, sweepstakes, barter, advertising, and pyramid schemes,etc.
- Encourages, invites or solicits extra marital affairs or dating.
- You must use the ShubhSambandh.com Service in a manner consistent with any and all applicable local, state, and federal laws and regulations.
- If at any time ShubhSambandh.com is of the view in its sole discretion that your profile contains any information or material or content which is objectionable, unlawful or illegal, ShubhSambandh.com has the right in its sole discretion to either forthwith terminate your membership without refund of your subscription fees or delete such objectionable, illegal or unlawful information, material or content from your profile and allow you to continue as a Member.
6. **Copyright Policy.**

You may not post, distribute, or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior written consent of the owner of such proprietary rights. Without limiting the foregoing, if you believe that your work has been copied and posted on the Site through the ShubhSambandh.com Service in a way that constitutes copyright infringement, please provide our Copyright Agent with the following information: an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; a description of the copyrighted work that you claim has been infringed; a description of where the material that you claim is infringing is located on the Site; your address, telephone number, and email address; a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and where applicable a copy of the registration certificate proving registration of copyright or any other applicable intellectual property right; a statement by you, made under penalty of perjury, that the above information in your Notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf. ShubhSambandh.com 's Copyright Agent for Notice of claims of copyright infringement can be reached by writing to the Mumbai address located under the Help/Contact section on the site.

7. **Member Disputes.**

You are solely responsible for your interactions with other ShubhSambandh.com Members. ShubhSambandh.com reserves the right, but has no obligation, to monitor disputes between you and other Members.

8. **Privacy.**

Use  of  the  ShubhSambandh.com  Site  and/or  the  ShubhSambandh.com  Service  is governed by the ShubhSambandh.com Privacy Policy(click here to view the Privacy Policy).

9. **Disclaimers.**

ShubhSambandh.com is not responsible for any incorrect or inaccurate Content posted on the Site or in connection with the ShubhSambandh.com Service, whether caused by users visiting the Site, Members or by any of the equipment or programming associated with or utilized  in  the  Service,  nor  for  the  conduct  of  any  user  and/or  Member  of  the ShubhSambandh.com Service whether online or offline. ShubhSambandh.com assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration  of,  user  and/or  Member  communications.  ShubhSambandh.com  is  not responsible for any problems or technical malfunction of any telephone network or lines, computer on-line-systems, servers or providers, computer equipment, software, failure of email or players on account of technical problems or traffic congestion on the Internet or at any website or combination thereof, including injury or damage to users and/or Members or to any other person's computer related to or resulting from participating or downloading materials in connection with the ShubhSambandh.com Site and/or in connection with the ShubhSambandh.com Service. Under no circumstances will ShubhSambandh.com be responsible for any loss or damage to any person resulting from anyone's use of the Site or the Service and/or any Content posted on the ShubhSambandh.com Site or transmitted to ShubhSambandh.com  Members.  The  exchange  of  profile(s)  through  or  by ShubhSambandh.com should not in any way be construed as any offer but we may send you out recommendations from/by ShubhSambandh.com based on your preferences. ShubhSambandh.com shall not be responsible for any loss or damage to any individual arising  out  of,  or  subsequent  to,  relations  established  pursuant  to  the  use  of ShubhSambandh.com . The Site and the Service are provided "AS-IS AVALIABLE BASIS" and ShubhSambandh.com expressly disclaims any warranty of fitness for a particular purpose or non-infringement. ShubhSambandh.com cannot guarantee and does not promise any specific results from use of the Site and/or the ShubhSambandh.com Service.

10. **Limitation on Liability.**

Except  in  jurisdictions  where  such  provisions  are  restricted,  in  no  event  will ShubhSambandh.com be liable to you or any third person for any indirect, consequential, exemplary, incidental, special or punitive damages, including also lost profits arising from your use of the Site or the ShubhSambandh.com Service, even if ShubhSambandh.com has been advised of the possibility of such damages. Notwithstanding anything to the contrary contained herein, ShubhSambandh.com , liability to you for any cause whatsoever, and regardless of the form of the action, will at all times be limited to the amount paid, if any, by you to ShubhSambandh.com , for the Service during the term of membership.

11. **Disputes.**

If there is any dispute about or involving the Site and/or the Service, by using the Site, you agree that the dispute will be governed by the laws of India. You agree to the exclusive jurisdiction to the courts of Mumbai, India.

12. **Indemnity.**

You agree to indemnify and hold ShubhSambandh.com , its subsidiaries, directors, affiliates, officers, agents, and other partners and employees, harmless from any loss, liability, claim, or demand, including reasonable attorney's fees, made by any third party due to or arising out of your use of the Service in violation of this Agreement and/or arising from a breach of these Terms of Use and/or any breach of your representations and warranties set forth above.

**Other.**

- By becoming a Member of the Site / ShubhSambandh.com Service, you agree to receive certain specific emails from ShubhSambandh.com .
- This Agreement, accepted upon use of the Site and further affirmed by becoming a Member of the ShubhSambandh.com Service, contains the entire agreement between you and ShubhSambandh.com regarding the use of the Site and/or the Service. If any provision of this Agreement is held invalid, the remainder of this Agreement shall continue in full force and effect.
- You are under an obligation to report any misuse or abuse of the Site. If you notice any abuse or misuse of the Site or any thing which is in violation of this Agreement, you shall forthwith report such violation to ShubhSambandh.com by writing to Customer Care. On receipt of such complaint, ShubhSambandh.com may investigate such complaint and if necessary may terminate the membership of the Member responsible for such violation abuse or misuse without any refund of subscription fee. Any false complaint made by a Member shall make such Member liable for termination of his / her membership without any refund of the subscription fee.
13. **Password Security:**

A password must be chosen as part of the membership registration procedure. You agree not to provide or resell your usage of or access to our website to any third party and are entirely responsible for creating a password that is difficult to guess and for keeping it secure. You must instantly tell us at care@shubhsambandh.com and modify your password by altering your account details if you have cause to suspect that your profile is no longer secure.

14. **Third Party Website:**

`            `The users of ShubhSambandh.com acknowledge that we may permit third parties to offer our users services via the website or app, and that we may also charge you for these third-party services. In this respect, our business may enter into a revenue-sharing agreement with the relevant third party, but we are in no way responsible to you for their services.

`             `ShubhSambandh.com retains the right, at any time and without prior notice, to add, remove, alter, modify, or suspend all of our services. Members of Waytonikah.com should be able to notice the modification on the website.

By becoming a member of ShubhSambandh.com and/or using the Services of the Site, you unconditionally and irrevocably confirm that you have read and understood the above provisions and agree to abide by them. If you are not agreeing to any of the above terms and conditions please refrain yourself from registering on the Site.

This Agreement is an electronic document in terms of the Information Technology Act, 2000 and Rules there under pertaining to electronic records as applicable and amended. This electronic record is generated by a computer system and does not require any physical or digital signatures.

Please contact  us  at care@shubhsambandh.com with  any  questions  regarding  this Agreement.