export const orgList = [
  "Abeokuta",
  "Abidjan",
  "Accra",
  "Adelaide",
  "Agartala",
  "Ahmedabad",
  "Alaminos",
  "Allahabad",
  "Amravati",
  "Amritsar",
  "Amsterdam",
  "Antwerp",
  "Aravade",
  "Arouca",
  "Astrakhan",
  "Asunción",
  "Atlanta",
  "Auckland",
  "Austin",
  "Bahadurgarh",
  "Bahau",
  "Baku",
  "Baltimore",
  "Bangalore - Hare Krishna Hill",
  "Bangkok",
  "Barcelona",
  "Baroda",
  "Beed",
  "Belfast",
  "Belgaum",
  "Belo Horizonte",
  "Benin City",
  "Bergamo",
  "Berkeley",
  "Berlin",
  "Bhubaneswar",
  "Birmingham",
  "Bishkent",
  "Boise",
  "Boston",
  "Brahmapur - Hare Krishna Temple",
  "Brahmapur - Ram Govinda Temple",
  "Brampton",
  "Bratislava",
  "Brisbane",
  "Budapest",
  "Buenos Aires - Bhaktivedanta Center",
  "Buenos Aires - Capital Federal",
  "Bukit Mertajam",
  "Cakovec",
  "Calgary",
  "Canberra",
  "Cape Town",
  "Caracas",
  "Cardiff",
  "Catania",
  "Chamorshi",
  "Chandigarh",
  "Chennai",
  "Chicago",
  "Chita",
  "Chittagong - Sri Krishna Mandir",
  "Chittagong - Sri Sri Radha Madava",
  "Christchurch",
  "Cochabamba",
  "Coimbatore",
  "Cologne",
  "Colombo",
  "Columbus",
  "Coventry",
  "Curitiba",
  "Dallas",
  "Debe",
  "Denpasar",
  "Denver",
  "Detroit",
  "Dhaka - Banagram",
  "Dhaka - Swamibag",
  "Dnipropetrovsk",
  "Donetsk",
  "Dublin",
  "Durban",
  "Dushanbe",
  "Dwarka",
  "Edmonton",
  "Eger",
  "Ekaterinburg",
  "Enugu",
  "Gaborone",
  "Gadei Giri",
  "Gainesville",
  "George Town",
  "Georgetown",
  "Ghaziabad",
  "Gothenburg",
  "Grödinge",
  "Guadalajara",
  "Guayaquil",
  "Guntur",
  "Guwahati",
  "Hamburg",
  "Hamilton",
  "Hanamkonda",
  "Haridaspur",
  "Haridwar",
  "Hartford",
  "Heidelberg",
  "Helsinki",
  "Hillsboro",
  "Hong Kong",
  "Honolulu",
  "Houston",
  "Hyderabad",
  "Ibadan",
  "Imphal",
  "Indore",
  "Ipoh",
  "Irkutsk",
  "Jaipur",
  "Jakarta",
  "Jammu",
  "Jessore - Nitai Gaur Mandir",
  "Jessore - Sri Rup-Sanatan Mandir",
  "Jhansi",
  "Johannesburg",
  "Jos",
  "Kaduna",
  "Kampala",
  "Kanpur",
  "Kansas City",
  "Karlovac",
  "Kathmandu",
  "Katra",
  "Kaunas",
  "Kazan",
  "Kharki",
  "Kiev - Dmitrievskaya",
  "Kiev - Zoryany pereulok",
  "Kishinev",
  "Kisumu",
  "Klang",
  "Kokosovce",
  "Kolkata",
  "Krasnodar",
  "Kuala Lumpur",
  "Kuching",
  "Kumasi",
  "Kurjinovo",
  "Kurukshetra",
  "Labasa",
  "Lagos",
  "Laguna Beach",
  "Las Vegas",
  "Lautoka",
  "Leicester",
  "Leipzig",
  "Lenasia",
  "Lesmahagow",
  "Lima",
  "Lisbon",
  "Ljubljana",
  "Locarno",
  "Lomé",
  "London - Bhaktivedanta Manor",
  "London – Matchless Gift",
  "London - South Norwood",
  "Longdenville",
  "Los Angeles",
  "Los Corralitos Guaymallin",
  "Lucknow",
  "Ludhiana",
  "Lund",
  "Madrid",
  "Madurai",
  "Manchester",
  "Mandalay",
  "Mangalore",
  "Manila",
  "Marondera",
  "Mayapur",
  "Melbourne",
  "Mexico City",
  "Miami",
  "Minsk",
  "Moirang",
  "Mombasa",
  "Monterrey",
  "Moscow - Sri Jagannath Mandir",
  "Moscow - Sri Sri Radha Madhav",
  "Mumbai – Chowpatty",
  "Mumbai - Juhu",
  "Mumbai - Mira Road",
  "Munich",
  "Murmansk",
  "Musashino-City",
  "Myitkyina",
  "Mysore",
  "Málaga",
  "Nagpur",
  "Nairobi",
  "Nashik",
  "Nausori",
  "Nellore",
  "New Delhi - Chattarpur",
  "New Delhi - East of Kailash",
  "New Delhi - Panchsheel",
  "New Delhi - Punjabi Bagh",
  "New Delhi - Rohini",
  "New Mumbai - Kharghar",
  "New Orleans",
  "New York - Brooklyn",
  "New York - Krishna Balarama Temple",
  "New York - Long Island Temple",
  "New York - Second Avenue",
  "Newcastle",
  "Newcastle upon Tyne",
  "Nieuwegein",
  "Nigdi",
  "Nijny Novgorod",
  "Nikolaev",
  "Nizhny Tagil",
  "Nkawkaw",
  "Noida",
  "Novorossijsk",
  "Novosibirsk",
  "Nuernberg",
  "Omsk",
  "Orlando",
  "Osijek",
  "Oslo",
  "Ottawa",
  "Panama",
  "Pandharpur",
  "Paramaribo",
  "Paris",
  "Patna",
  "Pecs",
  "Pereira",
  "Perm",
  "Perth",
  "Philadelphia",
  "Phoenix",
  "Port Harcourt",
  "Porto Alegre",
  "Potomac",
  "Prague",
  "Prai",
  "Pretoria",
  "Pula",
  "Pune",
  "Puri - Bhakti Kuti",
  "Puri - Bhaktivedanta Ashram",
  "Raipur",
  "Rajahmundry",
  "Rajkot",
  "Rakiraki",
  "Ranaghat",
  "Recife",
  "Regina",
  "Riga",
  "Rijeka",
  "Rio de Janeiro",
  "Rome",
  "Rosario",
  "Rose Belle",
  "Rostov-Na-Donu",
  "Saint Augustine",
  "Saint Louis",
  "Salem",
  "Saltillo",
  "Salvador",
  "Samara",
  "San Antonio",
  "San Diego",
  "San Jose",
  "San Miguel",
  "San Salvador",
  "Santa Cruz de la Sierra",
  "Santiago",
  "Santo Domingo",
  "Sao Paulo",
  "Sarajevo",
  "Seattle",
  "Secunderabad",
  "Septon-Durbuy",
  "Seremban",
  "Sigatoka",
  "Silchar",
  "Siliguri",
  "Simbirsk",
  "Skopje",
  "Sochi",
  "Sofia - Kjuri Street",
  "Sofia - Malinova Dolina",
  "Solapur",
  "Spanish Fork",
  "Srirangam",
  "Stockholm",
  "Sukhumi",
  "Sungai Petani",
  "Sunyani",
  "Surat",
  "Suva",
  "Suzano",
  "Swansea",
  "Sydney",
  "Sydney - New Gokula",
  "Sylhet",
  "Tai Pei City",
  "Taiping",
  "Takoradi",
  "Tallahassee",
  "Tallinn",
  "Tarkwa",
  "Tbilisi",
  "Tel Aviv",
  "Teluk Intan",
  "Thiruvananthapuram",
  "Timisoara",
  "Tirunelveli",
  "Tirupati",
  "Toronto",
  "Towaco",
  "Trier",
  "Tucson",
  "Udhampur",
  "Ujjain",
  "Ulan-Ude",
  "Vacoas-Phoenix",
  "Vallabh Vidyanagar",
  "Vancouver",
  "Vanlose",
  "Varanasi",
  "Vellore",
  "Vicenza",
  "Vijayawada",
  "Vilnius",
  "Vinnica",
  "Visakhapatnam",
  "Vladimir",
  "Vladivostok",
  "Vrindavan",
  "Warangal",
  "Warri",
  "Warsaw",
  "Wellington",
  "Wiesbaden",
  "Williamsburg",
  "Yogyakarta",
  "Zagreb",
  "Zurich",
];

export const initiatingGurus = [
  "Adikarta Das",
  "Asita Krishna Swami (TKG)",
  "Atmanivedana Swami (BSDS)",
  "Badrinarayan Swami",
  "Bhaktivaibhava Swami",
  "Bhakti Bhagavatamrita Kesava Swami (PVS)",
  "Bhakti Bhrnga Govinda Swami",
  "Bhakti Caitanya Swami",
  "Bhakti Carudesna Swami (BTS)",
  "Bhakti Dhira Damodara Swami (BTS)",
  "Bhakti Gaurava Narayan Swami (TKG)",
  "Bhakti Gauravani Goswami",
  "Bhakti Prabhupada-vrata Damodara Swami",
  "Bhakti Prema Swami (BCS)",
  "Bhakti Raghava Swami",
  "Bhakti Ratnakara Ambarisa Swami (GKG)",
  "Bhakti Sundar Goswami",
  "Bhakti Vasudeva Swami (BTS)",
  "Bhakti Vijnana Goswami (RNS)",
  "Bhakti Vikasa Swami",
  "Bhaktivyasa Tirtha Swami (BSDS)",
  "Bhakti VV Narasimha Swami",
  "Bhakti-bhusana Swami",
  "Bhaktimarga Swami",
  "Bhurijana Das",
  "Bir Krsna Das Goswami",
  "Caitanya Candra Das (GGS)",
  "Caitanya Candra Caran Das (JPS)",
  "Candra Mukha Swami (HDG)",
  "Candramauli Swami",
  "Caru Das",
  "Danavir Goswami",
  "Devamrita Swami",
  "Dhanvantari Swami",
  "Dhirasanta Das Goswami",
  "Drutakarma Das",
  "Gauranga Prem Swami (JPS)",
  "Giridhari Swami",
  "Giriraja Swami",
  "Gopaswami Das",
  "Gopal Krsna Goswami",
  "Guru Prasad Swami",
  "Haladhara Swami",
  "Hanumatpresaka Swami",
  "Harivilas Das",
  "Hrdayananda dasa Goswami",
  "Indradyumna Swami",
  "Janananda dasa Goswami",
  "Jayapataka Swami",
  "Jivananda Das",
  "Kalakantha Das",
  "Kavicandra Swami",
  "Kesava Bharati dasa Goswami",
  "Kratu Das",
  "Kripamoya Das",
  "Krsna Ksetra Swami",
  "Lokanath Swami",
  "Madhu Sevita Das",
  "Mahadyuti Swami",
  "Mahaman Das",
  "Mahatma Das",
  "Mahavisnu Swami",
  "Manonatha Das",
  "Matsya Avatara Das",
  "Medhavi Das",
  "Narayani Devi Dasi",
  "Navayogendra Swami",
  "Niranjana Swami",
  "Partha Sarathi Das Goswami",
  "Patita Pavana Das (IDS)",
  "Prahladananda Swami",
  "Purushatraya Swami",
  "Radhacaran Das (TKG)",
  "Radha Govinda Das (SRS)",
  "Radha Govinda Swami",
  "Radha Krishna Das (TKG)",
  "Radhanath Swami",
  "Rama Govinda Swami (KDS)",
  "Ravindra Svarupa Das",
  "Romapada Swami",
  "Rtadhvaja Swami",
  "Sacinandana Swami",
  "Samik Rsi Das",
  "Sankarsana Das",
  "Sivarama Swami",
  "Smita Krsna Swami",
  "Srivas Das (BTS)",
  "Subhaga Swami",
  "Sukadeva Swami (RNS)",
  "Suresvara Das",
  "Trivikrama Swami",
  "Vaisesika Das",
  "Varsana Swami",
  "Vedavyasapriya Swami",
  "Virabahu Das",
  "Yadunandana Swami",
  "Yamunacarya Das Goswami (HDG)",
  "Bhakti Visrambha Madhava Swami",
  "Bhanu Swami",
  "Ganapati Swami",
  "Jayadvaita Swami",
  "Mukunda Goswami",
  "Satsvarupa Das Goswami",
  "Satyadeva Das",
  "Vegavan Das",
];

export const books = [
  "Bhagavad-gita As It Is",
  "Srimad-Bhagavatam",
  "Sri Caitanya-caritamrta",
  "Teachings of Lord Caitanya",
  "The Nectar of Devotion",
  "The Nectar of Instruction",
  "Easy Journey to Other Planets",
  "Krsna Consciousness The Topmost Yoga System",
  "KRSNA, The Supreme Personality of Godhead",
  "Perfect Questions, Perfect Answers",
  "Teachings of Lord Kapila, the Son of Devahuti",
  "Teachings of Queen Kunti",
  "Krsna, the Reservoir of Pleasure",
  "The Science of Self Realization",
  "The Path of Perfection",
  "Life Comes From Life",
  "The Perfection of Yoga",
  "Beyond Birth and Death",
  "On the Way to Krsna",
  "Raja - Vidya: The King of Knowledge",
  "Elevation to Krsna Consciousness",
  "Krsna Consciousness, The Matchless Gift",
  "Light of the Bhagavata",
  "Sri Isopanisad",
  "The Journey of Self - Discovery",
  "Transcendental Teachings of Prahlada Maharaja",
  "A Second Chance: The Story of a Near - Death Experience",
  "Mukunda - mala - stotra",
  "Narada-bhakti-sutra",
];

export const hobbies = [
  "Adventure and Outdoor Activities",
  "Arts and Crafts",
  "Collecting Antiques or Coins",
  "Community Service",
  "Cooking",
  "Cycling and Trekking",
  "Dancing",
  "DIY Projects and Home Decor",
  "Fashion and Styling",
  "Fitness and Yoga",
  "Food and Dining",
  "Gaming",
  "Gardening",
  "Hiking and Nature Walks",
  "Learning New Languages",
  "Meditation and Spirituality",
  "Movies and Theatre",
  "Music",
  "Painting",
  "Pets and Animal Care",
  "Photography",
  "Reading",
  "Singing",
  "Sports",
  "Social Causes and Volunteering",
  "Teaching and Mentoring",
  "Technology and Gadgets",
  "Travelling",
  "Writing and Poetry",
  "Writing Blogs or Articles",
];

export const sportslist = [
  "Archery",
  "Athletics/Track Field",
  "Badminton",
  "Basketball",
  "Billiards and Snooker",
  "Boxing",
  "Carrom",
  "Chess",
  "Cricket",
  "Cycling",
  "Equestrian",
  "Fencing",
  "Football",
  "Golf",
  "Gymnastics",
  "Hockey",
  "Kabaddi",
  "Kho Kho",
  "Martial Arts",
  "Motorsports",
  "Polo",
  "Rowing",
  "Sailing",
  "Shooting",
  "Swimming",
  "Squash",
  "Table Tennis",
  "Tennis",
  "Volleyball",
  "Weightlifting",
  "Wrestling",
  "Yoga",
];

export const careers = [
  "Accountants and Auditors",
  "Actors, Producers, and Directors",
  "Actuaries",
  "Administrative Services Managers",
  "Adult Literacy and High School Equivalency Diploma Teachers",
  "Advertising Sales Agents",
  "Advertising, Marketing, Promotions, Public Relations, and Sales Managers",
  "Aerospace Engineering and Operations Technicians",
  "Aerospace Engineers",
  "Agricultural and Food Science Technicians",
  "Agricultural and Food Scientists",
  "Agricultural Engineers",
  "Agricultural Workers",
  "Air Traffic Controllers",
  "Aircraft and Avionics Equipment Mechanics and Service Technicians",
  "Aircraft Pilots and Flight Engineers",
  "Animal Care and Service Workers",
  "Announcers",
  "Anthropologists and Archeologists",
  "Appraisers and Assessors of Real Estate",
  "Arbitrators, Mediators, and Conciliators",
  "Architects, Except Landscape and Naval",
  "Architectural and Engineering Managers",
  "Archivists, Curators, and Museum Technicians",
  "Art Directors",
  "Artists and Related Workers",
  "Assemblers and Fabricators",
  "Athletes, Coaches, Umpires, and Related Workers",
  "Athletic Trainers",
  "Atmospheric Scientists",
  "Audiologists",
  "Automotive Body and Related Repairers",
  "Automotive Service Technicians and Mechanics",
  "Bakers",
  "Barbers, Cosmetologists, and Other Personal Appearance Workers",
  "Bartenders",
  "Bill and Account Collectors",
  "Billing and Posting Clerks and Machine Operators",
  "Biological Scientists",
  "Biological Technicians",
  "Biomedical Engineers",
  "Boilermakers",
  "Bookbinders and Bindery Workers",
  "Bookkeeping, Accounting, and Auditing Clerks",
  "Brickmasons, Blockmasons, and Stonemasons",
  "Broadcast and Sound Engineering Technicians and Radio Operators",
  "Brokerage Clerks",
  "Budget Analysts",
  "Building Cleaning Workers",
  "Bus Drivers",
  "Butchers",
  "Cardiovascular Technologists and Technicians",
  "Career and Technical Education Teachers",
  "Cargo and Freight Agents",
  "Carpenters",
  "Carpet, Floor, and Tile Installers and Finishers",
  "Cartographers and Photogrammetrists",
  "Cashiers",
  "Cement Masons, Concrete Finishers, Segmental Pavers, and Terrazzo Workers",
  "Chefs and Head Cooks",
  "Chefs, Cooks, and Food Preparation Workers",
  "Chemical Engineers",
  "Chemical Technicians",
  "Chemists and Materials Scientists",
  "Child Care Workers",
  "Chiropractors",
  "Civil Engineering Technicians",
  "Civil Engineers",
  "Claims Adjusters, Appraisers, Examiners, and Investigators",
  "Clinical Laboratory Technologists and Technicians",
  "Coaches and Scouts",
  "Coin, Vending, and Amusement Machine Servicers and Repairers",
  "Commercial and Industrial Designers",
  "Communications Equipment Operators",
  "Compensation and Benefits Managers",
  "Compensation, Benefits, and Job Analysis Specialists",
  "Computer and Information Research Scientists",
  "Computer and Information Systems Managers",
  "Computer Control Programmers and Operators",
  "Computer Hardware Engineers",
  "Computer Network Architects",
  "Computer Operators",
  "Computer Programmers",
  "Computer Scientists and Database Administrators",
  "Computer Software Engineers",
  "Computer Support Specialists",
  "Computer Support Specialists and Systems Administrators",
  "Computer Systems Analysts",
  "Computer, Automated Teller, and Office Machine Repairers",
  "Conservation Scientists and Foresters",
  "Construction and Building Inspectors",
  "Construction Equipment Operators",
  "Construction Laborers",
  "Construction Laborers and Helpers",
  "Construction Managers",
  "Cooks",
  "Correctional Officers",
  "Correctional Officers and Bailiffs",
  "Cost Estimators",
  "Counselors",
  "Counter and Rental Clerks",
  "Couriers and Messengers",
  "Court Reporters",
  "Craft and Fine Artists",
  "Credit Authorizers, Checkers, and Clerks",
  "Customer Service Representatives",
  "Dancers and Choreographers",
  "Data Entry and Information Processing Workers",
  "Database Administrators",
  "Delivery Truck Drivers and Driver/Sales Workers",
  "Demonstrators, Product Promoters, and Models",
  "Dental and Ophthalmic Laboratory Technicians and Medical Appliance Technicians",
  "Dental Assistants",
  "Dental Hygienists",
  "Dentists",
  "Desktop Publishers",
  "Diagnostic Medical Sonographers",
  "Diesel Service Technicians and Mechanics",
  "Dietitians and Nutritionists",
  "Dispatchers",
  "Drafters",
  "Drywall and Ceiling Tile Installers, and Tapers",
  "Drywall Installers, Ceiling Tile Installers, and Tapers",
  "Economists",
  "Editors",
  "Education Administrators",
  "Electrical and Electronics Engineering Technicians",
  "Electrical and Electronics Engineers",
  "Electrical and Electronics Installers and Repairers",
  "Electricians",
  "Electro-mechanical Technicians",
  "Electronic Home Entertainment Equipment Installers and Repairers",
  "Elementary, Middle, and High School Principals",
  "Elevator Installers and Repairers",
  "Emergency Management Directors",
  "Emergency Medical Technicians and Paramedics",
  "EMTs and Paramedics",
  "Engineering and Natural Sciences Managers",
  "Engineering Technicians",
  "Environmental Engineering Technicians",
  "Environmental Engineers",
  "Environmental Science and Protection Technicians",
  "Environmental Scientists and Hydrologists",
  "Environmental Scientists and Specialists",
  "Epidemiologists",
  "Exercise Physiologists",
  "Farmers, Ranchers, and Agricultural Managers",
  "Farmers, Ranchers, and Other Agricultural Managers",
  "Fashion Designers",
  "File Clerks",
  "Film and Video Editors and Camera Operators",
  "Financial Analysts",
  "Financial Analysts and Personal Financial Advisors",
  "Financial Clerks",
  "Financial Examiners",
  "Financial Managers",
  "Fire Fighting Occupations",
  "Fire Inspectors",
  "Firefighters",
  "Fishers and Fishing Vessel Operators",
  "Fishing and Hunting Workers",
  "Fitness Trainers and Instructors",
  "Fitness Workers",
  "Flight Attendants",
  "Flooring Installers and Tile and Marble Setters",
  "Floral Designers",
  "Food and Beverage Serving and Related Workers",
  "Food and Tobacco Processing Workers",
  "Food Processing Occupations",
  "Food Service Managers",
  "Forensic Science Technicians",
  "Forest and Conservation Workers",
  "Forest, Conservation, and Logging Workers",
  "Fundraisers",
  "Funeral Directors",
  "Funeral Service Workers",
  "Gaming Cage Workers",
  "Gaming Services Occupations",
  "Gaming Services Workers",
  "General Maintenance and Repair Workers",
  "General Office Clerks",
  "Genetic Counselors",
  "Geographers",
  "Geological and Petroleum Technicians",
  "Geoscientists",
  "Glaziers",
  "Graphic Designers",
  "Grounds Maintenance Workers",
  "Hand Laborers and Material Movers",
  "Hazardous Materials Removal Workers",
  "Health and Safety Engineers",
  "Health Educators",
  "Health Educators and Community Health Workers",
  "Heating, Air Conditioning, and Refrigeration Mechanics and Installers",
  "Heating, Air-Conditioning, and Refrigeration Mechanics and Installers",
  "Heavy and Tractor-trailer Truck Drivers",
  "Heavy Vehicle and Mobile Equipment Service Technicians",
  "Heavy Vehicle and Mobile Equipment Service Technicians and Mechanics",
  "High School Teachers",
  "Historians",
  "Home Appliance Repairers",
  "Home Health Aides and Personal Care Aides",
  "Hotel, Motel, and Resort Desk Clerks",
  "Human Resources Assistants, Except Payroll and Timekeeping",
  "Human Resources Managers",
  "Human Resources Specialists",
  "Human Resources, Training, and Labor Relations Managers and Specialists",
  "Hydrologists",
  "Industrial Designers",
  "Industrial Engineering Technicians",
  "Industrial Engineers",
  "Industrial Machinery Mechanics and Maintenance Workers",
  "Industrial Production Managers",
  "Information Clerks",
  "Information Security Analysts",
  "Inspectors, Testers, Sorters, Samplers, and Weighers",
  "Instructional Coordinators",
  "Insulation Workers",
  "Insurance Sales Agents",
  "Insurance Underwriters",
  "Interior Designers",
  "Interpreters and Translators",
  "Ironworkers",
  "Jewelers and Precious Stone and Metal Workers",
  "Job Opportunities in the Armed Forces",
  "Judges and Hearing Officers",
  "Judges, Magistrates, and Other Judicial Workers",
  "Kindergarten and Elementary School Teachers",
  "Labor Relations Specialists",
  "Landscape Architects",
  "Lawyers",
  "Librarians",
  "Library Technicians and Assistants",
  "Licensed Practical and Licensed Vocational Nurses",
  "Line Installers and Repairers",
  "Loan Officers",
  "Lodging Managers",
  "Logging Workers",
  "Logisticians",
  "Machine Setters, Operators, and Tenders-Metal and Plastic",
  "Machinists",
  "Machinists and Tool and Die Makers",
  "Maintenance and Repair Workers, General",
  "Management Analysts",
  "Manicurists and Pedicurists",
  "Marine Engineers and Naval Architects",
  "Market and Survey Researchers",
  "Market Research Analysts",
  "Marriage and Family Therapists",
  "Massage Therapists",
  "Material Moving Machine Operators",
  "Material Moving Occupations",
  "Material Recording Clerks",
  "Materials Engineers",
  "Mathematicians",
  "Mathematicians and Statisticians",
  "Mechanical Engineering Technicians",
  "Mechanical Engineers",
  "Medical and Clinical Laboratory Technologists and Technicians",
  "Medical and Health Services Managers",
  "Medical Assistants",
  "Medical Equipment Repairers",
  "Medical Records and Health Information Technicians",
  "Medical Scientists",
  "Medical Transcriptionists",
  "Medical, Dental, and Ophthalmic Laboratory Technicians",
  "Meeting and Convention Planners",
  "Meeting, Convention, and Event Planners",
  "Metal and Plastic Machine Workers",
  "Microbiologists",
  "Middle School Teachers",
  "Military Careers",
  "Millwrights",
  "Mining and Geological Engineers",
  "Models",
  "Meter Readers, Utilities",
  "Multimedia Artists and Animators",
  "Music Directors and Composers",
  "Musicians and Singers",
  "Musicians, Singers, and Related Workers",
  "Natural Sciences Managers",
  "Network and Computer Systems Administrators",
  "News Analysts, Reporters, and Correspondents",
  "Nuclear Engineers",
  "Nuclear Medicine Technologists",
  "Nuclear Technicians",
  "Nurse Anesthetists, Nurse Midwives, and Nurse Practitioners",
  "Nursing Assistants and Orderlies",
  "Nursing, Psychiatric, and Home Health Aides",
  "Occupational Health and Safety Specialists and Technicians",
  "Occupational Therapist Assistants and Aides",
  "Occupational Therapists",
  "Occupational Therapy Assistants and Aides",
  "Office and Administrative Support Worker Supervisors and Managers",
  "Office Clerks, General",
  "Operations Research Analysts",
  "Opticians",
  "Opticians, Dispensing",
  "Optometrists",
  "Order Clerks",
  "Orthotists and Prosthetists",
  "Painters and Paperhangers",
  "Painters, Construction and Maintenance",
  "Painting and Coating Workers",
  "Painting and Coating Workers, Except Construction and Maintenance",
  "Paralegals and Legal Assistants",
  "Payroll and Timekeeping Clerks",
  "Personal and Home Care Aides",
  "Personal Financial Advisors",
  "Pest Control Workers",
  "Petroleum Engineers",
  "Pharmacists",
  "Pharmacy Aides",
  "Pharmacy Technicians",
  "Phlebotomists",
  "Photographers",
  "Physical Therapist Assistants and Aides",
  "Physical Therapists",
  "Physician Assistants",
  "Physicians and Surgeons",
  "Physicists and Astronomers",
  "Pipelayers, Plumbers, Pipefitters, and Steamfitters",
  "Photographic Process Workers and Processing Machine Operators",
  "Plumbers, Pipefitters, and Steamfitters",
  "Podiatrists",
  "Police and Detectives",
  "Police, Fire, and Ambulance Dispatchers",
  "Political Scientists",
  "Postal Service Workers",
  "Postsecondary Education Administrators",
  "Postsecondary Teachers",
  "Plasterers and Stucco Masons",
  "Power Plant Operators, Distributors, and Dispatchers",
  "Preschool and Childcare Center Directors",
  "Preschool Teachers",
  "Private Detectives and Investigators",
  "Probation Officers and Correctional Treatment Specialists",
  "Procurement Clerks",
  "Producers and Directors",
  "Production, Planning, and Expediting Clerks",
  "Property, Real Estate, and Community Association Managers",
  "Precision Instrument and Equipment Repairers",
  "Psychiatric Technicians and Aides",
  "Prepress Technicians and Workers",
  "Psychologists",
  "Public Relations and Fundraising Managers",
  "Public Relations Specialists",
  "Purchasing Managers, Buyers, and Purchasing Agents",
  "Printing Machine Operators",
  "Quality Control Inspectors",
  "Radiation Therapists",
  "Radio and Telecommunications Equipment Installers and Repairers",
  "Radiologic and MRI Technologists",
  "Radiologic Technologists and Technicians",
  "Rail Transportation Occupations",
  "Railroad Workers",
  "Real Estate Brokers and Sales Agents",
  "Receptionists",
  "Receptionists and Information Clerks",
  "Recreation Workers",
  "Recreational Therapists",
  "Registered Nurses",
  "Rehabilitation Counselors",
  "Reporters, Correspondents, and Broadcast News Analysts",
  "Reservation and Transportation Ticket Agents and Travel Clerks",
  "Respiratory Therapists",
  "Retail Sales Workers",
  "Retail Salespersons",
  "Roofers",
  "Sales Engineers",
  "Sales Managers",
  "Sales Representatives, Wholesale and Manufacturing",
  "School and Career Counselors",
  "Secretaries and Administrative Assistants",
  "Securities, Commodities, and Financial Services Sales Agents",
  "Security Guards and Gaming Surveillance Officers",
  "Sheet Metal Workers",
  "Shipping, Receiving, and Traffic Clerks",
  "Skincare Specialists",
  "Small Engine Mechanics",
  "Social and Community Service Managers",
  "Social and Human Service Assistants",
  "Social Scientists, Other",
  "Social Workers",
  "Sales Worker Supervisors",
  "Sociologists",
  "Software Developers",
  "Science Technicians",
  "Solar Photovoltaic Installers",
  "Special Education Teachers",
  "Speech-Language Pathologists",
  "Stationary Engineers and Boiler Operators",
  "Semiconductor Processors",
  "Statisticians",
  "Stock Clerks and Order Fillers",
  "Structural and Reinforcing Iron and Metal Workers",
  "Substance Abuse, Behavioral Disorder, and Mental Health Counselors",
  "Surgical Technologists",
  "Survey Researchers",
  "Surveying and Mapping Technicians",
  "Surveyors",
  "Surveyors, Cartographers, Photogrammetrists, and Surveying and Mapping Technicians",
  "Tax Examiners and Collectors, and Revenue Agents",
  "Tax Examiners, Collectors, and Revenue Agents",
  "Taxi Drivers and Chauffeurs",
  "Taxi Drivers, Ride-Hailing Drivers, and Chauffeurs",
  "Teacher Assistants",
  "Teachers-Adult Literacy and Remedial Education",
  "Teachers-Postsecondary",
  "Teachers-Preschool, Kindergarten, Elementary, Middle, and Secondary",
  "Teachers-Special Education",
  "Technical Writers",
  "Telecommunications Equipment Installers and Repairers",
  "Television, Video, and Motion Picture Camera Operators and Editors",
  "Tellers",
  "Tool and Die Makers",
  "Top Executives",
  "Training and Development Managers",
  "Training and Development Specialists",
  "Travel Agents",
  "Truck Drivers and Driver/Sales Workers",
  "Umpires, Referees, and Other Sports Officials",
  "Urban and Regional Planners",
  "Veterinarians",
  "Teachers-Self-Enrichment Education",
  "Veterinary Assistants and Laboratory Animal Caretakers",
  "Veterinary Technologists and Technicians",
  "Waiters and Waitresses",
  "Water and Liquid Waste Treatment Plant and System Operators",
  "Water and Wastewater Treatment Plant and System Operators",
  "Water Transportation Occupations",
  "Textile, Apparel, and Furnishings Occupations",
  "Water Transportation Workers",
  "Web Developers",
  "Weighers, Measurers, Checkers, and Samplers, Recordkeeping",
  "Welders, Cutters, Solderers, and Brazers",
  "Welding, Soldering, and Brazing Workers",
  "Wholesale and Manufacturing Sales Representatives",
  "Wind Turbine Technicians",
  "Woodworkers",
  "Writers and Authors",
  "Writers and Editors",
  "Zoologists and Wildlife Biologists",
];


export const age_range: string[] = [
  'Younger than me',
  'Same age as me',
  'Older than me',
  'No specific preference'
];

export const marital_status = ['Never Married', 'Divorced', 'Awaiting Divorce', 'Widowed', 'Separated'];

export const devotional_preferences = ['Connected to ISKCON', 'No specific preference'];

export const diet = [
  'Vegetarian',
  'Non-vegetarian',
  'Vegan',
  'Jain (no root vegetables)',
  'Sattvik (no onion/garlic)'
];

export const location = [
  'Same city as me',
  'Same state as me',
  'Same country as me',
  'Different country but willing to relocate',
  'No specific preference'
];

export const family_background = [
  'Traditional and Cultured',
  'Modern and Open-minded',
  'Balanced mix of Traditional and Modern Values',
  'No specific preference'
];

export const annual_income = [
  'Less than 1,00,000',
  '1,00,000-3,00,000',
  '3,00,001-5,00,000',
  '5,00,001-8,00,000',
  '8,00,001-12,00,000',
  '12,00,001-15,00,000',
  '15,00,001-20,00,000',
  '20,00,001-25,00,000',
  'Greater than 25,00,000',
  'No specific preference'
];

export const occupation = [
  'Professional/White-collar job',
  'Business/Self-employed',
  'Skilled/Technical job',
  'Not employed',
  'Homemaker',
  'No specific preference'
];

export const education = [
  'High School or Below',
  "Bachelor's Degree",
  "Master's Degree",
  'Doctorate or Professional Degree'
];

export const rashi = [
  'Mesh (Aries)',
  'Karka (Cancer)',
  'Tula (Libra)',
  'Makar (Capricorn)',
  'Vrisabh (Taurus)',
  'Simha (Leo)',
  'Vrishchik (Scorpio)',
  'Kumbha (Aquarius)',
  'Mithuna (Gemini)',
  'Kanya (Virgo)',
  'Dhanu (Sagittarius)',
  'Meen (Pisces)'
];
